# -*- coding: utf-8 -*-
"""U-Net Implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/kumarikanak/254381203742483cbe0ddce4f64945e6/u-net-implementation.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

# for data load
import os

# for reading and processing images
import imageio
from PIL import Image

# for visualizations
import matplotlib.pyplot as plt

import numpy as np # for using np arrays

# for bulding and running deep learning model
import tensorflow as tf
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout 
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import concatenate
from tensorflow.keras.losses import binary_crossentropy
from sklearn.model_selection import train_test_split

def LoadData (path1, path2):
    """
    Looks for relevant filenames in the shared path
    Returns 2 lists for original and masked files respectively
    
    """
    # Read the images folder like a list
    image_dataset = os.listdir(path1)
    mask_dataset = os.listdir(path2)

    # Make a list for images and masks filenames
    orig_img = []
    mask_img = []
    for file in image_dataset:
        orig_img.append(file)
    for file in mask_dataset:
        mask_img.append(file)

    # Sort the lists to get both of them in same order (the dataset has exactly the same name for images and corresponding masks)
    orig_img.sort()
    mask_img.sort()
    
    return orig_img, mask_img

# def PreprocessData(img, mask, target_shape_img, target_shape_mask, path1, path2):
#     """
#     Processes the images and mask present in the shared list and path
#     Returns a NumPy dataset with images as 3-D arrays of desired size
#     Please note the masks in this dataset have only one channel
#     """
#     # Pull the relevant dimensions for image and mask
#     m = len(img)                     # number of images
#     i_h,i_w,i_c = target_shape_img   # pull height, width, and channels of image
#     m_h,m_w,m_c = target_shape_mask  # pull height, width, and channels of mask
    
#     # Define X and Y as number of images along with shape of one image
#     X = np.zeros((m,i_h,i_w,i_c), dtype=np.float32)
#     y = np.zeros((m,m_h,m_w,m_c), dtype=np.int32)
    
#     # Resize images and masks
#     for file in img:
#         # convert image into an array of desired shape (3 channels)
#         index = img.index(file)
#         path = os.path.join(path1, file)
#         single_img = Image.open(path).convert('RGB')
#         single_img = single_img.resize((i_h,i_w))
#         single_img = np.reshape(single_img,(i_h,i_w,i_c)) 
#         single_img = single_img/256.
#         X[index] = single_img
        
#         # convert mask into an array of desired shape (1 channel)
#         single_mask_ind = mask[index]
#         path = os.path.join(path2, single_mask_ind)
#         single_mask = Image.open(path)
#         #plt.imshow(single_mask)
#         single_mask = single_mask.resize((m_h, m_w))
#         single_mask = np.array(single_mask)
#         single_mask = single_mask[:,:,0]
#         single_mask = np.reshape(single_mask,(m_h,m_w,m_c)) 
#         single_mask[single_mask==255] = 1
#         y[index] = single_mask
#     return X, y

def EncoderMiniBlock(inputs, n_filters=32, dropout_prob=0.3, max_pooling=True):
    """
    This block uses multiple convolution layers, max pool, relu activation to create an architecture for learning. 
    Dropout can be added for regularization to prevent overfitting. 
    The block returns the activation values for next layer along with a skip connection which will be used in the decoder
    """
    # Add 2 Conv Layers with relu activation and HeNormal initialization using TensorFlow 
    # Proper initialization prevents from the problem of exploding and vanishing gradients 
    # 'Same' padding will pad the input to conv layer such that the output has the same height and width (hence, is not reduced in size) 
    conv = Conv2D(n_filters, 
                  3,   # Kernel size   
                  activation='relu',
                  padding='same',
                  kernel_initializer='HeNormal')(inputs)
    conv = Conv2D(n_filters, 
                  3,   # Kernel size
                  activation='relu',
                  padding='same',
                  kernel_initializer='HeNormal')(conv)
    
    # Batch Normalization will normalize the output of the last layer based on the batch's mean and standard deviation
    conv = BatchNormalization()(conv, training=False)

    # In case of overfitting, dropout will regularize the loss and gradient computation to shrink the influence of weights on output
    if dropout_prob > 0:     
        conv = tf.keras.layers.Dropout(dropout_prob)(conv)

    # Pooling reduces the size of the image while keeping the number of channels same
    # Pooling has been kept as optional as the last encoder layer does not use pooling (hence, makes the encoder block flexible to use)
    # Below, Max pooling considers the maximum of the input slice for output computation and uses stride of 2 to traverse across input image
    if max_pooling:
        next_layer = tf.keras.layers.MaxPooling2D(pool_size = (2,2))(conv)    
    else:
        next_layer = conv

    # skip connection (without max pooling) will be input to the decoder layer to prevent information loss during transpose convolutions      
    skip_connection = conv
    
    return next_layer, skip_connection

def DecoderMiniBlock(prev_layer_input, skip_layer_input, n_filters=32):
    """
    Decoder Block first uses transpose convolution to upscale the image to a bigger size and then,
    merges the result with skip layer results from encoder block
    Adding 2 convolutions with 'same' padding helps further increase the depth of the network for better predictions
    The function returns the decoded layer output
    """
    # Start with a transpose convolution layer to first increase the size of the image
    up = Conv2DTranspose(
                 n_filters,
                 (3,3),    # Kernel size
                 strides=(2,2),
                 padding='same')(prev_layer_input)

    # Merge the skip connection from previous block to prevent information loss
    merge = concatenate([up, skip_layer_input], axis=3)
    
    # Add 2 Conv Layers with relu activation and HeNormal initialization for further processing
    # The parameters for the function are similar to encoder
    conv = Conv2D(n_filters, 
                 3,     # Kernel size
                 activation='relu',
                 padding='same',
                 kernel_initializer='HeNormal')(merge)
    conv = Conv2D(n_filters,
                 3,   # Kernel size
                 activation='relu',
                 padding='same',
                 kernel_initializer='HeNormal')(conv)
    return conv

"""
   Combine both encoder and decoder blocks according to the U-Net research paper
   Return the model as output 
   """
def UNetCompiled(input_size=(128, 128, 3), n_filters=32, n_classes=2):
  #print("Hiii")
  # Input size represent the size of 1 image (the size used for pre-processing) 
  inputs = Input(input_size)

  # Encoder includes multiple convolutional mini blocks with different maxpooling, dropout and filter parameters
  # Observe that the filters are increasing as we go deeper into the network which will increasse the # channels of the image 
  cblock1 = EncoderMiniBlock(inputs, n_filters,dropout_prob=0, max_pooling=True)
  cblock2 = EncoderMiniBlock(cblock1[0],n_filters*2,dropout_prob=0, max_pooling=True)
  cblock3 = EncoderMiniBlock(cblock2[0], n_filters*4,dropout_prob=0, max_pooling=True)
  cblock4 = EncoderMiniBlock(cblock3[0], n_filters*8,dropout_prob=0.3, max_pooling=True)
  cblock5 = EncoderMiniBlock(cblock4[0], n_filters*16, dropout_prob=0.3, max_pooling=False)

  # Decoder includes multiple mini blocks with decreasing number of filters
  # Observe the skip connections from the encoder are given as input to the decoder
  # Recall the 2nd output of encoder block was skip connection, hence cblockn[1] is used
  ublock6 = DecoderMiniBlock(cblock5[0], cblock4[1],  n_filters * 8)
  ublock7 = DecoderMiniBlock(ublock6, cblock3[1],  n_filters * 4)
  ublock8 = DecoderMiniBlock(ublock7, cblock2[1],  n_filters * 2)
  ublock9 = DecoderMiniBlock(ublock8, cblock1[1],  n_filters)

  # Complete the model with 1 3x3 convolution layer (Same as the prev Conv Layers)
  # Followed by a 1x1 Conv layer to get the image to the desired size. 
  # Observe the number of channels will be equal to number of output classes
  conv9 = Conv2D(n_filters,
                 3,
                 activation='relu',
                 padding='same',
                 kernel_initializer='he_normal')(ublock9)

  conv10 = Conv2D(n_classes, 1, padding='same')(conv9)

  # Define the model
  model = tf.keras.Model(inputs=inputs, outputs=conv10)
  return model

""" Load Train Set and view some examples """
# Call the apt function
path1 = '/content/drive/MyDrive/Documents/Pan_Cards/'
path2 = '/content/drive/MyDrive/Documents/Pan_Masks/'
img, mask = LoadData (path1, path2)

print(img)
print(mask)

# View an example of image and corresponding mask 
show_images = 4
for i in range(show_images):
    img_view  = imageio.imread(path1 + img[i])
    mask_view = imageio.imread(path2 + mask[i])
    print(np.unique(mask_view[:,:,0]))
    mask_view = mask_view[:,:,0]
    print(img_view.shape)
    print(mask_view.shape)
    fig, arr = plt.subplots(1, 2, figsize=(15, 15))
    arr[0].imshow(img_view)
    arr[0].set_title('Image '+ str(i))
    arr[1].imshow(mask_view)
    arr[1].set_title('Masked Image '+ str(i))

# imgs, masks = [], []
# for i in range(len(img)):
#   img_path = os.path.join(path1, img[i])
#   mask_path = os.path.join(path2, mask[i])

#   image = Image.open(img_path)
#   mask_new = Image.open(mask_path)

#   mask_arr = np.array(mask_new)[:,:,0]
#   mask_arr[mask_arr==255] = 1
#   mask_new = Image.fromarray(mask_arr)
  
#   mask_new.convert('1')
#   imgs.append(np.array(image.resize((128, 128)))/256.)
#   masks.append(np.array(mask_new.resize((128, 128))))

# imgs, masks = np.array(imgs), np.array(masks)

# masks = np.expand_dims(masks, axis=-1)
# print("Image Size: ", imgs.shape)
# print("Masks Size: ", masks.shape)

# Define the desired shape
imgs, masks = [], []
for i in range(len(img)):
  img_path = os.path.join(path1, img[i])
  mask_path = os.path.join(path2, mask[i])

  image = Image.open(img_path)
  mask_new = Image.open(mask_path)

  mask_arr = np.array(mask_new)[:,:,0]
  mask_arr[mask_arr==255] = 1
  mask_new = Image.fromarray(mask_arr)
  
  mask_new.convert('1')
  imgs.append(np.array(image.resize((128, 128)))/256.)
  masks.append(np.array(mask_new.resize((128, 128))))
imgs, masks = np.array(imgs), np.array(masks)

masks = np.expand_dims(masks, axis=-1)
print("Image Size: ", imgs.shape)
print("Masks Size: ", masks.shape)

print(np.unique(masks))

#Visualize the output
image_index = 44
fig, arr = plt.subplots(1, 2, figsize=(15, 15))
arr[0].imshow(imgs[image_index])
arr[0].set_title('Processed Image')
arr[1].imshow(masks[image_index,:,:,0])
arr[1].set_title('Processed Masked Image ')

X_train, X_valid, y_train, y_valid = train_test_split(imgs, masks, test_size=0.2, random_state=123)

# Call the helper function for defining the layers for the model, given the input image size
unet = UNetCompiled(input_size=(128,128,3), n_filters=32, n_classes=2)

# Check the summary to better interpret how the output dimensions change in each layer
unet.summary()

# There are multiple optimizers, loss functions and metrics that can be used to compile multi-class segmentation models
# Ideally, try different options to get the best accuracy
unet.compile(optimizer=tf.keras.optimizers.Adam(), 
             loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Run the model in a mini-batch fashion and compute the progress for each epoch
results = unet.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_valid, y_valid))

unet.save("/content/drive/MyDrive/Documents/unet_model.h5")

unet.evaluate(X_valid, y_valid)

# Results of Validation Dataset
def VisualizeResults(index):
    img = X_valid[index]
    img = img[np.newaxis, ...]
    pred_y = unet.predict(img)
    pred_mask = tf.argmax(pred_y[0], axis=-1)
    pred_mask = pred_mask[..., tf.newaxis]
    fig, arr = plt.subplots(1, 3, figsize=(15, 15))
    arr[0].imshow(X_valid[index])
    arr[0].set_title('Processed Image')
    arr[1].imshow(y_valid[index,:,:,0])
    arr[1].set_title('Actual Masked Image ')
    arr[2].imshow(pred_mask[:,:,0])
    arr[2].set_title('Predicted Masked Image ')

VisualizeResults(53)

model = tf.keras.models.load_model('/content/drive/MyDrive/Documents/unet_model.h5')

import cv2
from google.colab.patches import cv2_imshow


# img = Image.open('/content/drive/MyDrive/Documents/test_unet/10_pfront.jpeg')
# img = Image.open('/content/drive/MyDrive/Documents/test_unet/31_pfront.jpeg')
img = Image.open('/content/drive/MyDrive/Documents/test_unet/49_pfront.jpeg')
#img = Image.open('/content/drive/MyDrive/Documents/test_unet/53_pfront.jpeg')
#img = Image.open('/content/drive/MyDrive/Documents/PanCards/BQRPM0521N.jpg')
w, h = img.size
print('width: ', w)
print('height:', h)
img_arr = np.array(img)
img = np.array(img.resize((128, 128)))/256.
org = img
plt.imshow(img_arr)
img_arr.shape
plt.imshow(img)
img.shape
plt.imshow(org)
org.shape

img = img[np.newaxis, ...]
img.shape

prediction = model.predict(img)
#prediction = unet.predict(img)
pred_mask = tf.argmax(prediction[0], axis=-1)
pred_mask = pred_mask[..., tf.newaxis]
pred_mask
np.unique(pred_mask)
pred_mask.shape
pred_array = pred_mask.numpy()
pred_array
np.unique(pred_array)
pred_array.shape

fig, arr = plt.subplots(1, 2, figsize=(10, 10))
arr[0].imshow(org)
    # arr[0].set_title('Processed Image')
    # arr[1].imshow(y_valid[index,:,:,0])
    # arr[1].set_title('Actual Masked Image ')
masked_img = pred_mask[:,:,0]
arr[1].imshow(masked_img,cmap="gray")
arr[1].set_title('Predicted Masked Image ')
output_arr = masked_img.numpy()
np.unique(output_arr)

plt.imsave('/content/drive/MyDrive/Documents/test_unet/masks/output.jpg', output_arr, cmap='gray')

import cv2
import imutils
import numpy as np
from skimage import exposure
from google.colab.patches import cv2_imshow

output = cv2.imread('/content/drive/MyDrive/Documents/test_unet/masks/output.jpg')
mask = output
cv2_imshow(output)
output.shape
msk_arr = np.array(output)
#plt.imshow(org)

imgray = cv2.cvtColor(output,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(imgray,127,255,cv2.THRESH_BINARY)
# find contours 
contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
# straight rectangle
x,y,w,h = cv2.boundingRect(cnt)
img= cv2.rectangle(output,(x,y),(x+w,y+h),(0,255,0),2)
cv2_imshow(img)
print(x,y,w,h)
output.shape

# img = cv2.imread('/content/drive/MyDrive/Documents/test_unet/53_pfront.jpeg')
img = cv2.imread('/content/drive/MyDrive/Documents/test_unet/49_pfront.jpeg')
# img = cv2.imread('/content/drive/MyDrive/Documents/test_unet/10_pfront.jpeg')
#img = cv2.imread('/content/drive/MyDrive/Documents/test_unet/31_pfront.jpeg')
#img = cv2.imread('/content/drive/MyDrive/Documents/PanCards/BQRPM0521N.jpg')
#cv2_imshow(img)
width , height = img.shape[:2]
if(width > 500 and height > 500):
  img = cv2.resize(img,(512,512))
print(width,height)
img.shape

new_width, new_height = img.shape[:2]

resized_mask = cv2.resize(msk_arr,(new_height,new_width))
cv2_imshow(resized_mask)
resized_mask.shape

cont_mask = np.copy(resized_mask)
#cv2_imshow(cont_mask)
#cont_mask.shape
imgray = cv2.cvtColor(cont_mask,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(imgray,127,255,cv2.THRESH_BINARY)
# find contours 
contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
# straight rectangle
x,y,w,h = cv2.boundingRect(cnt)
cont_mask= cv2.rectangle(cont_mask,(x,y),(x+w,y+h),(0,255,0),2)
cv2_imshow(cont_mask)
cv2_imshow(resized_mask)
cv2_imshow(img)

print(img.shape)
print(resized_mask.shape)
out = cv2.bitwise_and(img,resized_mask)
cv2_imshow(out)
out.shape
out_arr = np.copy(out)
#cv2.imwrite("/content/drive/MyDrive/Documents/test_unet/Output/res.jpg",out)

out_cont= cv2.rectangle(out_arr,(x,y),(x+w,y+h),(0,255,0),2)
cv2_imshow(out_cont)

left_top = [x,y]        #A
left_bot = [x,y+h]      #B
right_bot = [x+w,y+h]   #C
right_top = [x+w,y]     #D
print(left_top,left_bot,right_bot,right_top)

width_top = np.sqrt(((left_top[0] - right_top[0]) ** 2) + ((left_top[1] - right_top[1]) ** 2))
width_bot = np.sqrt(((left_bot[0] - right_bot[0]) ** 2) + ((left_bot[1] - right_bot[1]) ** 2))
maxWidth = max(int(width_top), int(width_bot))
 
 
height_left = np.sqrt(((left_top[0] - left_bot[0]) ** 2) + ((left_top[1] - left_bot[1]) ** 2))
height_right = np.sqrt(((right_bot[0] - right_top[0]) ** 2) + ((right_bot[1] - right_top[1]) ** 2))
maxHeight = max(int(height_left), int(height_right))
print(maxWidth,maxHeight)

input_pts = np.float32([left_top, left_bot, right_bot, right_top])
output_pts = np.float32([[0, 0],
                        [0, maxHeight - 1],
                        [maxWidth - 1, maxHeight - 1],
                        [maxWidth - 1, 0]])

# Compute the perspective transform M
M = cv2.getPerspectiveTransform(input_pts,output_pts)

warped = cv2.warpPerspective(out,M,(maxWidth, maxHeight),flags=cv2.INTER_LINEAR)
cv2_imshow(warped)
cv2.imwrite("/content/drive/MyDrive/Documents/test_unet/Cropped/crop.jpg",warped)

